name: tests

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Run tests
        run: dart test
